export const DELETE_EXCERCISE = 'DELETE_EXCERCISE'

export const CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE'
export const CHANGE_SELECTION = 'CHANGE_SELECTION'

export const ADD_LINK = 'ADD_LINK'
export const ADD_SPLIT = 'ADD_SPLIT'

export const SHOW_DIARY = 'SHOW_DIARY'

export const SELECT_EXCERCISES_FOR_NEW_SPLIT = 'SELECT_EXCERCISES_FOR_NEW_SPLIT'
export const SELECT_DATE_FOR_NEW_SPLIT = 'SELECT_DATE_FOR_NEW_SPLIT'
export const ADD_SET_IN_NEW_SPLIT = 'ADD_SET_IN_NEW_SPLIT'
export const DELETE_EXCERCISE_FROM_NEW_SPLIT = 'DELETE_EXCERCISE_FROM_NEW_SPLIT'
export const DELETE_EXCERCISE_FROM_SELECT = 'DELETE_EXCERCISE_FROM_SELECT'

export const OPEN_EXCERCISE_SELECT = 'OPEN_EXCERCISE_SELECT'
export const CLOSE_EXCERCISE_SELECT = 'CLOSE_EXCERCISE_SELECT'

export const ADD_RATE = 'ADD_RATE'

export const ADD = '_ADD'
export const REMOVE = '_REMOVE'
